<?php

namespace TM\BlogBundle\Entity;

/**
 * SubcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByCat($cat)
	{
	  $qb = $this
	    ->createQueryBuilder('s')
	    ->leftJoin('s.category', 'cat')
	    ->addSelect('cat')
	    ->where('cat.name = :name')
	    ->setParameter('name', $cat)
	  ;

	  return $qb
	    ->getQuery()
	    ->getResult()
	  ;
	}

    public function full()
    {
        $qb = $this->createQueryBuilder('s')
             ->leftJoin('s.category', 'c')
             ->addSelect('c');

        return $qb 	->getQuery()
            		->getResult();
    }

    public function nav($name)
    {
        $qb = $this->createQueryBuilder('s')
             ->leftJoin('s.category', 'c')
             ->addSelect('c')
             ->where('c.name = :name')
	    	 ->setParameter('name', $name);

        return $qb  ->getQuery()
                    ->getResult();
    }
}
