<?php
// src/TM/UserBundle/Entity/UserRepository.php

namespace TM\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function formFilter($uId)
    {
        $qb = $this->createQueryBuilder('u')
             ->where('u.id = :id')
             ->setParameter('id', (int)$uId);

        return $qb  ->getQuery()
                    ->getResult();
    }
}
